# name: Deploy_Test_Container

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - "packages/container/**"
# defaults:
#   run:
#     working-directory: packages/container
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id:${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key:${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ap-south-1
#       - name: Use Node.js 16.x
#         uses: actions/setup-node@v1
#         with:
#           node-version: 16.x
#       - name: Install dependencies
#         run: npm install
#       - name: Build
#         run: npm run build
#       - run: pwd
#       - run: ls -la ./dist
#       - name: Deploy
#         run: aws s3 sync ./dist s3://${{ secrets.AWS_ACCESS_KEY_ID }}